language: ruby
sudo: false
cache: bundler
before_install:
- gem install bundler
gemfile:
  - Gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
before_script:
- createdb test
rvm:
- '2.3.0'
- '2.2.2'
notifications:
  email: false
env:
  global:
  - secure: OvcOmU3tTrRrgXAAZpZVMbgwtxL7NtF35hf1sBhR8K+x1zZvcJkO1ADc60zzcXsMSIfavsD6uUPE0V92OJ+AgJPJq85skXr0UaYWmCDsEcnCqCl3HQYph1d6ntzZ2ZVC7Oz/nwuk2oaTL02wXuh/2XsztvDSTHWsNAWye787u4mPU4n4YXggsSCIU6zHSz5orfkKR4DkXT7jhrVP6lIn+an+j4RyZJ2Y7HE32vtV93bq1bdSiyJNs0fOY6iGpPRoD86mO2dRSdpQPPI4y0ArnPH6dFiWTIy94xWNyb64vvzDCqsJdj1A/4h13AUNqK5rG8nuWllWCe455o17fTPJchqM71ImjrOyeHFPkGvkID2UL0tgIApNl3bBdANWDITXLeJiAtDHIlFcisxda2qJs3pe4YM+UkspInofHvO80YFT4/IBfYB1bbWwcP8+bisvpUoStjZXO7VPAilxVC+RimGK1vp74WLHm1LQGkINpeEhFyhAxYyuOGHhTLlfquVAhQbCy6bV78NHeoxpTBjt6u0ZpBlDe9yJXO0NsRqyhCSKf+4LNpafROpxCU4BvT4WYi7QM3cJgO7Mlia67YzVrl3IYKkOctvcfj3pdlxTWlcd0RzEBj8Xicq+3tCgJ1mkMqExIylXQwYGflP77ErCw4hcC6wsWYhBl/wQMC/+VWE=
  - secure: mYZG8lgc+9qJiS0CZ5RiZJzmFnT2ePyCR799GQwBHTwT+r8zUJtUAsXtt/EO5PJOBcTbcWfXl1xa+ktXKF5lG0SKHBsOn4dXOEkfSCCpMR2ahSPudsI9VlLAPwLLmCUpbIFZm/m42LD0kernr6h11Htc7dZ7/yK6i9VP5a64koujouoO1/o41UF+6dU8A/KUIPnNAjhcCHYjYxSk8rt0Oh12++RflfdDbhZpqm4hDNPvjDBtZW6AvZ9849kslC0kyWRsWfhtuyJqQKIg445QaGMfTccsNd5Uu8HhOH24bajXr30LZ0vGVvN2pto4L6G/rWrfT59yg3aFcXEmURZ+WGw5xnBMsG7mlu0/HsqWxzS8r2k7UWCv7SleFPbhI6QUc7n8FSVbTZzVkVg5n4M+e44HGk83e6quSvZLOa7B7R2atho24mVyx+14DVRtY3TJuD3xr4A6TKbKXU/8lo69idqfVly4UdZvFAzous/T9X5MKfNblGOZV0zlbUn6aBQMUyjSMbhIiGbYzzd2AldgLfbCSD2mTrS2MmAmNYXPNHucR3p04O0xkzKH01jGRIaakV2sLihIWr5sZTlv4JgQDYYuyWtg/+N++TVDyb2+9BH6zOkyNa7FtKLHVbEpQrl+ru5LYiXgSTa/kkdftrbxlqa+wLqMx05Uu8rUoEgv9Ok=
