language: ruby
sudo: false
cache: bundler
before_install:
- gem install bundler
gemfile:
- Gemfile
- gemfiles/rails_5_0.gemfile
- gemfiles/rails_5_1.gemfile
- gemfiles/rails_5_2.gemfile
before_script:
- createdb test
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
rvm:
- 2.5.2
notifications:
  email: false
env:
  global:
    secure: ad7XyZUN30m+SZVC0z471B9WuI8MAXzr5IMYrw6LN3zNMi046nvYsHAbKHZ0kqmhR3auzNN2o7+gc+AjlzXhM3kaVN2lvN3HUE6ghZIYx13PJngPbwsnD4gl5xwkasdtasEuIbQeoHr08pnlLvh0q/YX5LK03FlExBzTPeTvf4QQmWvfagtnw1YTBfSNHh3VVAH7NIh9gatATvjaUyCAPmQbFVPWVO+oEm+27iwb/edRHrcs77wfqAjDVnPYrQLm1TnCyuU7viQa7uSKe5eKmM3yOKQ+gcJPFfdzGDssME+scmyBnnmL5IgFaHyetFsCGDEUvbkGNZJeSAfptSrx0R9hmtw/pyGG2ClX7g6Lr9v+ei1RmIoNKdjOpsNMKLA+Ykhh+QCStQ4smdbbkFvG6m8Ul4L+rGQrhMv75yA12h7o7HRD3QUGNX4QLjXm0HToJUjvEly/cOHulQFocb6Zpdjmzq0fZPxZaHTrK/dOPchzrV2e5BGBfTuz4zuai/gnU2YWzpx6GhejjS/QJk1xJqn0svgCbm2zBBZnMJbXpmtoGpWt/YJUleL1S0MjRbW/z9AP8XDOJ6GWdJ0NNVzPzi9Yn28DMpUWg13IyA9indOWwb0CyljGe/qFzFTwkTxS7tXQZymdARq+ZGac+u8zWFgy4IbBQ104E3xMAxtZzW4=
